#!/usr/bin/env bun

/**
 * capture-session-summary.ts - SessionEnd Hook
 *
 * Generates a session summary document when a Claude Code session ends,
 * documenting what was accomplished during the session.
 *
 * Reads tool outputs from .logs/tool-outputs/ and generates a markdown
 * summary in .logs/history/sessions/YYYY-MM/
 */

import { writeFileSync, mkdirSync, existsSync, readFileSync, readdirSync } from 'fs';
import { join } from 'path';

interface SessionData {
  conversation_id: string;
  timestamp: string;
  [key: string]: unknown;
}

interface SessionInfo {
  focus: string;
  filesChanged: string[];
  commandsExecuted: string[];
  toolsUsed: string[];
  duration: number;
}

async function main() {
  try {
    // Read input from stdin
    const input = await Bun.stdin.text();
    if (!input || input.trim() === '') {
      process.exit(0);
    }

    const data: SessionData = JSON.parse(input);

    // Generate timestamp for filename
    const now = new Date();
    const timestamp = now.toISOString()
      .replace(/:/g, '')
      .replace(/\..+/, '')
      .replace('T', '-'); // YYYY-MM-DD-HHMMSS

    const yearMonth = timestamp.substring(0, 7); // YYYY-MM

    // Analyze session from tool outputs
    const sessionInfo = await analyzeSession(data.conversation_id);

    // Generate filename
    const filename = `${timestamp}_session.md`;

    // Ensure directory exists
    const sessionDir = join(process.cwd(), '.logs', 'history', 'sessions', yearMonth);
    if (!existsSync(sessionDir)) {
      mkdirSync(sessionDir, { recursive: true });
    }

    // Generate session document
    const sessionDoc = formatSessionDocument(timestamp, data, sessionInfo);

    // Write session file
    writeFileSync(join(sessionDir, filename), sessionDoc);

    // Exit successfully
    process.exit(0);
  } catch (error) {
    // Silent failure - don't disrupt workflow
    console.error(`[Hook] SessionEnd error: ${error}`);
    process.exit(0);
  }
}

async function analyzeSession(conversationId: string): Promise<SessionInfo> {
  // Read tool outputs to analyze what happened in this session
  const toolOutputsDir = join(process.cwd(), '.logs', 'tool-outputs');

  const filesChanged: string[] = [];
  const commandsExecuted: string[] = [];
  const toolsUsed: Set<string> = new Set();

  try {
    if (existsSync(toolOutputsDir)) {
      const files = readdirSync(toolOutputsDir).filter(f => f.endsWith('.jsonl'));

      for (const file of files) {
        const filePath = join(toolOutputsDir, file);
        const content = readFileSync(filePath, 'utf-8');
        const lines = content.split('\n').filter(l => l.trim());

        for (const line of lines) {
          try {
            const entry = JSON.parse(line);

            // Check if this entry belongs to the current session
            if (entry.session === conversationId) {
              toolsUsed.add(entry.tool);

              // Extract file changes
              if (entry.tool === 'Edit' || entry.tool === 'Write') {
                if (entry.input?.file_path) {
                  filesChanged.push(entry.input.file_path);
                }
              }

              // Extract bash commands
              if (entry.tool === 'Bash' && entry.input?.command) {
                commandsExecuted.push(entry.input.command);
              }
            }
          } catch {
            // Skip invalid JSON lines
          }
        }
      }
    }
  } catch {
    // Silent failure
  }

  return {
    focus: 'development',
    filesChanged: [...new Set(filesChanged)].slice(0, 20), // Unique, max 20
    commandsExecuted: commandsExecuted.slice(0, 20), // Max 20
    toolsUsed: Array.from(toolsUsed),
    duration: 0 // Unknown
  };
}

function formatSessionDocument(timestamp: string, data: SessionData, info: SessionInfo): string {
  const date = timestamp.substring(0, 10); // YYYY-MM-DD
  const time = timestamp.substring(11).replace(/-/g, ':'); // HH:MM:SS

  return `---
type: session-summary
timestamp: ${new Date().toISOString()}
session_id: ${data.conversation_id}
---

# Session Summary

**Date:** ${date}
**Time:** ${time}
**Session ID:** ${data.conversation_id}

---

## Tools Used

${info.toolsUsed.length > 0 ? info.toolsUsed.map((t: string) => `- ${t}`).join('\n') : '- None recorded'}

---

## Files Modified

${info.filesChanged.length > 0 ? info.filesChanged.map((f: string) => `- \`${f}\``).join('\n') : '- None recorded'}

**Total Files Changed:** ${info.filesChanged.length}

---

## Commands Executed

${info.commandsExecuted.length > 0 ? '```bash\n' + info.commandsExecuted.join('\n') + '\n```' : 'None recorded'}

---

## Notes

This session summary was automatically generated by the SessionEnd hook.

For detailed tool outputs, see: \`.logs/tool-outputs/\`

---

**Generated:** ${new Date().toISOString()}
`;
}

main();
